# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_num', models.IntegerField()),
                ('has_audio', models.BooleanField()),
                ('standard_name', models.CharField(max_length=50)),
                ('standard_abbr', models.CharField(max_length=50)),
                ('official_abbr', models.CharField(max_length=50)),
                ('standard_singular_name', models.CharField(max_length=50)),
                ('standard_singular_abbr', models.CharField(max_length=50)),
                ('official_singular_abbr', models.CharField(max_length=50)),
                ('standard_plural_name', models.CharField(max_length=50)),
                ('standard_plural_abbr', models.CharField(max_length=50)),
                ('official_plural_abbr', models.CharField(max_length=50)),
                ('url_segment', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_num', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bible.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content_api', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnid', models.SlugField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_2_code', models.CharField(max_length=2, unique=True)),
                ('wt_code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_num', models.IntegerField()),
                ('content', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.Chapter')),
                ('footnotes', models.ManyToManyField(to='bible.Footnote')),
            ],
        ),
        migrations.CreateModel(
            name='VerseRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourced_relations', to='bible.Verse')),
            ],
        ),
        migrations.CreateModel(
            name='VerseRelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='verserelationship',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='bible.VerseRelationshipType'),
        ),
        migrations.AddField(
            model_name='verserelationship',
            name='to_verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_relations', to='bible.Verse'),
        ),
        migrations.AddField(
            model_name='verse',
            name='related_verses',
            field=models.ManyToManyField(through='bible.VerseRelationship', to='bible.Verse'),
        ),
        migrations.AddField(
            model_name='edition',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='bible.Language'),
        ),
        migrations.AddField(
            model_name='edition',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='bible.Translation'),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bible.Edition'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together=set([('language', 'translation')]),
        ),
    ]
