# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='edition_api',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
