# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_language_edition_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='verserelationshiptype',
            name='code',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('edition', 'book_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set([('book', 'chapter_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together=set([('chapter', 'verse_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='verserelationship',
            unique_together=set([('from_verse', 'to_verse')]),
        ),
    ]
