# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_book_chapter_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='fnid',
            field=models.SlugField(unique=True),
        ),
    ]
