# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0006_auto_20160214_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('edition', 'book_num')},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('book__edition', 'book__book_num', 'chapter_num')},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='footnote',
            options={'ordering': ('edition', 'fnid')},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('iso_2_code',)},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ('symbol',)},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ('chapter__book__edition', 'chapter__book__book_num', 'chapter__chapter_num', 'verse_num')},
        ),
        migrations.AlterModelOptions(
            name='verserelationship',
            options={'ordering': ('from_verse__chapter__book__edition', 'from_verse__chapter__book__book_num', 'from_verse__chapter__chapter_num', 'from_verse__verse_num', 'to_verse__chapter__book__edition', 'to_verse__chapter__book__book_num', 'to_verse__chapter__chapter_num', 'to_verse__verse_num', 'relationship_type__name')},
        ),
        migrations.AlterModelOptions(
            name='verserelationshiptype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='verse',
            name='footnotes',
            field=models.ManyToManyField(related_name='verses', to='bible.Footnote'),
        ),
        migrations.AlterUniqueTogether(
            name='verserelationship',
            unique_together=set([('relationship_type', 'from_verse', 'to_verse')]),
        ),
    ]
